#!/bin/sh

if [ -z "$API_KEY" ] || [ -z "$API_SECRET" ]
then
  export API_KEY=46314122
  export API_SECRET=69d2a025fa953655e0be749fd31fbb1fbff53429
fi

if [ -d "cache" ]
then
  rm -rf cache/
fi

php -S localhost:8080 -t web/
