#!/bin/sh

if [ -z "$API_KEY" ] || [ -z "$API_SECRET" ]
then
  # OpenTok Project Configuration (find these at https://tokbox.com/account)
  export API_KEY=46314122
  export API_SECRET=69d2a025fa953655e0be749fd31fbb1fbff53429

  # SIP Destination Configuration (find these with your SIP server provider)
  export SIP_URI=sip:
  export SIP_USERNAME=
  export SIP_PASSWORD=
  export SIP_SECURE=false

  # SIP from (optional)
  export SIP_FROM=003456@yourcompany.com
fi

if [ -d "cache" ]
then
  rm -rf cache/
fi

php -S localhost:8080 -t web/
